swift:
  - section_separator_line_swift: Line Separator
  - section_separator_dashed_swift: Dashed Separator
  - section_separator_text_swift: Text Separator
  - section_separator_children_swift: Children Separator
  - section_separator_vertical_swift: Vertical Separator
  - section_separator_props_swift: ""
